### ISSUE TITLE
Where is my diary?

### ISSUE THREAD

**Issue by romainSilvestri** [OnEstLarge/PROHEIG18#1]
I lost it

**Comment by mathieujee** [comment]
Where did you see it for the last time ?

**Comment by mathieujee** [comment]
Did you check your pockets ?

**Comment by romainSilvestri** [comment]
I think some tyrant might have destroy it...

**Comment by mathieujee** [comment]
The tyrant decided to close this issue.
Problem resolved.
Thank you for using ODeep (formerly Izi-Pedo), The best p2p Sharing app.
